config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # READ (All)
  get "/tasks", to: "tasks#index"

  # CREATE (One)
  get "/tasks/new", to: "tasks#new"
   # FORM (Submit New)
  post "/tasks", to: "tasks#create"

  # READ (One)
  get "/tasks/:id", to: "tasks#show", as: "task"

  # EDIT (Details)
  get "/tasks/:id/edit", to: "tasks#edit", as: "edit_task"
  # UPDATE (Update DB)
  patch "/tasks/:id", to: "tasks#update"

  # DELETE (One)
  delete "/tasks/:id", to: "tasks#destroy", as: "destroy_task"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  # READ (ALL)
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_param)
    @task.save
    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_param)
    redirect_to tasks_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_param
    params.require(:task).permit(:title, :details)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/css?family=Open+Sans|Roboto" rel="stylesheet">

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |info| %>

  <%= info.label :title %>
  <%= info.text_field :title %>

  <%= info.label :details %>
  <%= info.text_area :details %>

  <%= info.submit %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Title</h1>

<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<h2>Task list</h2>

<ul class="no-style">
  <% @tasks.each do |task| %>
    <li>
      <p>
        <% if task.completed? %>
          [x]
        <% else %>
          [_]
        <% end %>
        <%= link_to task.title, task_path(task.id), :class => "task-link" %>
      </p>
    </li>
  <% end %>
</ul>


<%= link_to "Create a new task", "/tasks/new", :class => "task-link" %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= form_for(@task) do |info| %>

  <%= info.label :title %>
  <%= info.text_field :title %>

  <%= info.label :details %>
  <%= info.text_area :details %>

  <%= info.submit %>
<% end %>

app/views/tasks/show.html.erb
<h2><%= @task.title %></h2>
<p>
<%= @task.details %>
</p>
<div> <%= link_to "back to list", "/tasks", :class => "task-link" %> </div>
<div> <%= link_to "edit task", edit_task_path(@task.id), :class => "task-link" %> </div>
<div> <%= link_to "delete task", destroy_task_path(@task.id), method: :delete, :class => "task-link" %> </div>